export const copy = {
  "pt-BR": {
    language: "Idioma",
    english: "English",
    portuguese: "Português (Brasil)",
    title: "FrameOPS",
    subtitle: "Gestão de projetos de pentest",
    signIn: "Entrar",
    email: "E-mail",
    password: "Senha",
    signInAction: "Iniciar sessão",
    signingIn: "Iniciando sessão…",
    portfolio: "Projetos de pentest",
    clients: "Clientes",
    clientName: "Nome do cliente",
    createClient: "Criar cliente",
    creatingClient: "Criando cliente…",
    selectClient: "Selecione um cliente",
    engagements: "Engagements",
    engagementName: "Nome do engagement",
    createEngagement: "Criar engagement",
    creatingEngagement: "Criando engagement…",
    noClients: "Nenhum cliente encontrado.",
    noEngagements: "Nenhum engagement encontrado.",
    selectEngagement: "Selecione um engagement",
    findings: "Achados",
    findingTitle: "Título do achado",
    description: "Descrição",
    impact: "Impacto",
    remediation: "Remediação",
    reproduction: "Reprodução",
    cvssVector: "Vetor CVSS 3.1",
    createFinding: "Registrar achado",
    creatingFinding: "Registrando achado…",
    noFindings: "Nenhum achado encontrado.",
    selectFinding: "Selecione um achado",
    score: "Score",
    validationState: "Validação",
    remediationState: "Remediação",
    confirmFinding: "Confirmar como aberto",
    confirmingFinding: "Confirmando achado…",
    retests: "Retestes",
    resultState: "Resultado",
    procedure: "Procedimento executado",
    observedResult: "Resultado observado",
    justification: "Justificativa",
    recordRetest: "Registrar reteste",
    recordingRetest: "Registrando reteste…",
    noRetests: "Nenhum reteste registrado.",
    evidence: "Evidências",
    evidenceFile: "Arquivo de evidência",
    captureEvidence: "Capturar evidência",
    capturingEvidence: "Capturando evidência…",
    noEvidence: "Nenhuma evidência capturada.",
    sessionReady: "Sessão iniciada.",
    loading: "Carregando…",
    errorGeneric: "Não foi possível concluir a operação. Tente novamente.",
    errorSession: "Sua sessão expirou. Entre novamente.",
    errorInvalidRequest: "Confira os dados e tente novamente.",
    errorInvalidCVSS: "Informe um vetor CVSS 3.1 válido.",
    errorInvalidState: "O estado atual não permite esta operação.",
    errorEvidenceTooLarge: "O arquivo de evidência excede o limite de 32 MiB.",
    errorForbidden: "Você não tem permissão para esta operação.",
    errorNotFound: "O item solicitado não foi encontrado.",
    noClientSelected: "Selecione um cliente antes de criar um engagement.",
    methodologies: "Metodologias",
    methodologyName: "Nome da metodologia",
    sourceName: "Fonte",
    sourceVersion: "Versão da fonte",
    attribution: "Atribuição",
    checklistItemTitle: "Item do checklist",
    checklistObjective: "Objetivo",
    checklistProcedure: "Procedimento",
    createMethodology: "Criar metodologia",
    creatingMethodology: "Criando metodologia…",
    publishMethodology: "Publicar",
    publishingMethodology: "Publicando…",
    selectMethodology: "Selecione uma metodologia publicada",
    noMethodologies: "Nenhuma metodologia publicada encontrada.",
    noMethodologySelected: "Selecione uma metodologia publicada antes de criar um engagement.",
    checklist: "Checklist do engagement",
    noChecklist: "Nenhum checklist selecionado.",
    reports: "Relatórios",
    reportFile: "Arquivo DOCX",
    uploadReport: "Enviar relatório",
    uploadingReport: "Enviando relatório…",
    approveReport: "Aprovar revisão",
    approvingReport: "Aprovando revisão…",
    derivePDF: "Derivar PDF",
    derivingPDF: "Derivando PDF…",
    noReports: "Nenhuma revisão de relatório enviada.",
    derivedPDF: "PDF derivado",
    errorReportTooLarge: "O relatório excede o limite de 32 MiB.",
    errorConversionFailed: "Não foi possível derivar o PDF. Tente novamente.",
    overview: "Visão geral",
    projects: "Projetos",
    integrations: "Integrações e CLI",
    workspace: "Workspace do engagement",
    noEngagementSelected: "Selecione ou crie um engagement para começar o trabalho operacional.",
    engagementContext: "Contexto ativo",
    clientContext: "Cliente",
    projectContext: "Projeto",
    workbench: "Bancada operacional",
    workbenchDescription: "Selecione um projeto para concentrar checklist, achados, evidências e entrega.",
    projectSummary: "O trabalho deste engagement aparece aqui, sem misturar fluxos de outras etapas.",
    cliTitle: "CLI online",
    cliDescription: "Use a CLI durante os testes e consolide aqui os registros estruturados do engagement.",
    integrationDescription: "As integrações preservam a mesma API, organização e trilha de auditoria do workspace.",
    selectWorkspace: "Selecionar workspace",
    projectChecklist: "Checklist do projeto",
    loadingWorkspace: "Carregando workspace…",
  },
  en: {
    language: "Language",
    english: "English",
    portuguese: "Português (Brasil)",
    title: "FrameOPS",
    subtitle: "Pentest project management",
    signIn: "Sign in",
    email: "Email",
    password: "Password",
    signInAction: "Start session",
    signingIn: "Starting session…",
    portfolio: "Pentest projects",
    clients: "Clients",
    clientName: "Client name",
    createClient: "Create client",
    creatingClient: "Creating client…",
    selectClient: "Select a client",
    engagements: "Engagements",
    engagementName: "Engagement name",
    createEngagement: "Create engagement",
    creatingEngagement: "Creating engagement…",
    noClients: "No clients found.",
    noEngagements: "No engagements found.",
    selectEngagement: "Select an engagement",
    findings: "Findings",
    findingTitle: "Finding title",
    description: "Description",
    impact: "Impact",
    remediation: "Remediation",
    reproduction: "Reproduction",
    cvssVector: "CVSS 3.1 vector",
    createFinding: "Record finding",
    creatingFinding: "Recording finding…",
    noFindings: "No findings found.",
    selectFinding: "Select a finding",
    score: "Score",
    validationState: "Validation",
    remediationState: "Remediation",
    confirmFinding: "Confirm as open",
    confirmingFinding: "Confirming finding…",
    retests: "Retests",
    resultState: "Result",
    procedure: "Executed procedure",
    observedResult: "Observed result",
    justification: "Justification",
    recordRetest: "Record retest",
    recordingRetest: "Recording retest…",
    noRetests: "No retests recorded.",
    evidence: "Evidence",
    evidenceFile: "Evidence file",
    captureEvidence: "Capture evidence",
    capturingEvidence: "Capturing evidence…",
    noEvidence: "No evidence captured.",
    sessionReady: "Session started.",
    loading: "Loading…",
    errorGeneric: "We could not complete the operation. Try again.",
    errorSession: "Your session expired. Sign in again.",
    errorInvalidRequest: "Check the information and try again.",
    errorInvalidCVSS: "Enter a valid CVSS 3.1 vector.",
    errorInvalidState: "The current state does not allow this operation.",
    errorEvidenceTooLarge: "The evidence file exceeds the 32 MiB limit.",
    errorForbidden: "You do not have permission for this operation.",
    errorNotFound: "The requested item was not found.",
    noClientSelected: "Select a client before creating an engagement.",
    methodologies: "Methodologies",
    methodologyName: "Methodology name",
    sourceName: "Source",
    sourceVersion: "Source version",
    attribution: "Attribution",
    checklistItemTitle: "Checklist item",
    checklistObjective: "Objective",
    checklistProcedure: "Procedure",
    createMethodology: "Create methodology",
    creatingMethodology: "Creating methodology…",
    publishMethodology: "Publish",
    publishingMethodology: "Publishing…",
    selectMethodology: "Select a published methodology",
    noMethodologies: "No published methodologies found.",
    noMethodologySelected: "Select a published methodology before creating an engagement.",
    checklist: "Engagement checklist",
    noChecklist: "No checklist selected.",
    reports: "Reports",
    reportFile: "DOCX file",
    uploadReport: "Upload report",
    uploadingReport: "Uploading report…",
    approveReport: "Approve revision",
    approvingReport: "Approving revision…",
    derivePDF: "Derive PDF",
    derivingPDF: "Deriving PDF…",
    noReports: "No report revisions uploaded.",
    derivedPDF: "Derived PDF",
    errorReportTooLarge: "The report exceeds the 32 MiB limit.",
    errorConversionFailed: "We could not derive the PDF. Try again.",
    overview: "Overview",
    projects: "Projects",
    integrations: "Integrations and CLI",
    workspace: "Engagement workspace",
    noEngagementSelected: "Select or create an engagement to begin operational work.",
    engagementContext: "Active context",
    clientContext: "Client",
    projectContext: "Project",
    workbench: "Operations workbench",
    workbenchDescription: "Select a project to focus its checklist, findings, evidence, and delivery.",
    projectSummary: "This engagement's work appears here without mixing work from other stages.",
    cliTitle: "Online CLI",
    cliDescription: "Use the CLI during testing and consolidate the engagement's structured records here.",
    integrationDescription: "Integrations retain the same API, organization, and audit trail as the workspace.",
    selectWorkspace: "Select workspace",
    projectChecklist: "Project checklist",
    loadingWorkspace: "Loading workspace…",
  },
} as const;

export type Locale = keyof typeof copy;

export function apiErrorMessage(code: string, locale: Locale) {
  const text = copy[locale];
  switch (code) {
    case "unauthorized":
    case "invalid_credentials":
      return text.errorSession;
    case "invalid_request":
      return text.errorInvalidRequest;
    case "invalid_cvss_vector":
      return text.errorInvalidCVSS;
    case "invalid_state":
      return text.errorInvalidState;
    case "evidence_too_large":
      return text.errorEvidenceTooLarge;
    case "report_too_large":
      return text.errorReportTooLarge;
    case "conversion_failed":
      return text.errorConversionFailed;
    case "forbidden":
      return text.errorForbidden;
    case "not_found":
      return text.errorNotFound;
    default:
      return text.errorGeneric;
  }
}
