export const copy = {
  "pt-BR": {
    language: "Idioma",
    english: "English",
    portuguese: "Português (Brasil)",
    title: "FrameOPS",
    subtitle: "Gestão de projetos de pentest",
    signIn: "Entrar",
    email: "E-mail",
    password: "Senha",
    signInAction: "Iniciar sessão",
    signingIn: "Iniciando sessão…",
    portfolio: "Projetos de pentest",
    clients: "Clientes",
    clientName: "Nome do cliente",
    createClient: "Criar cliente",
    creatingClient: "Criando cliente…",
    selectClient: "Selecione um cliente",
    engagements: "Engagements",
    engagementName: "Nome do engagement",
    createEngagement: "Criar engagement",
    creatingEngagement: "Criando engagement…",
    noClients: "Nenhum cliente encontrado.",
    noEngagements: "Nenhum engagement encontrado.",
    selectEngagement: "Selecione um engagement",
    findings: "Achados",
    findingTitle: "Título do achado",
    description: "Descrição",
    impact: "Impacto",
    remediation: "Remediação",
    reproduction: "Reprodução",
    cvssVector: "Vetor CVSS 3.1",
    createFinding: "Registrar achado",
    creatingFinding: "Registrando achado…",
    noFindings: "Nenhum achado encontrado.",
    selectFinding: "Selecione um achado",
    score: "Score",
    validationState: "Validação",
    remediationState: "Remediação",
    confirmFinding: "Confirmar como aberto",
    confirmingFinding: "Confirmando achado…",
    retests: "Retestes",
    resultState: "Resultado",
    procedure: "Procedimento executado",
    observedResult: "Resultado observado",
    justification: "Justificativa",
    recordRetest: "Registrar reteste",
    recordingRetest: "Registrando reteste…",
    noRetests: "Nenhum reteste registrado.",
    sessionReady: "Sessão iniciada.",
    loading: "Carregando…",
    errorGeneric: "Não foi possível concluir a operação. Tente novamente.",
    errorSession: "Sua sessão expirou. Entre novamente.",
    errorInvalidRequest: "Confira os dados e tente novamente.",
    errorInvalidCVSS: "Informe um vetor CVSS 3.1 válido.",
    errorInvalidState: "O estado atual não permite esta operação.",
    errorForbidden: "Você não tem permissão para esta operação.",
    errorNotFound: "O item solicitado não foi encontrado.",
    noClientSelected: "Selecione um cliente antes de criar um engagement.",
  },
  en: {
    language: "Language",
    english: "English",
    portuguese: "Português (Brasil)",
    title: "FrameOPS",
    subtitle: "Pentest project management",
    signIn: "Sign in",
    email: "Email",
    password: "Password",
    signInAction: "Start session",
    signingIn: "Starting session…",
    portfolio: "Pentest projects",
    clients: "Clients",
    clientName: "Client name",
    createClient: "Create client",
    creatingClient: "Creating client…",
    selectClient: "Select a client",
    engagements: "Engagements",
    engagementName: "Engagement name",
    createEngagement: "Create engagement",
    creatingEngagement: "Creating engagement…",
    noClients: "No clients found.",
    noEngagements: "No engagements found.",
    selectEngagement: "Select an engagement",
    findings: "Findings",
    findingTitle: "Finding title",
    description: "Description",
    impact: "Impact",
    remediation: "Remediation",
    reproduction: "Reproduction",
    cvssVector: "CVSS 3.1 vector",
    createFinding: "Record finding",
    creatingFinding: "Recording finding…",
    noFindings: "No findings found.",
    selectFinding: "Select a finding",
    score: "Score",
    validationState: "Validation",
    remediationState: "Remediation",
    confirmFinding: "Confirm as open",
    confirmingFinding: "Confirming finding…",
    retests: "Retests",
    resultState: "Result",
    procedure: "Executed procedure",
    observedResult: "Observed result",
    justification: "Justification",
    recordRetest: "Record retest",
    recordingRetest: "Recording retest…",
    noRetests: "No retests recorded.",
    sessionReady: "Session started.",
    loading: "Loading…",
    errorGeneric: "We could not complete the operation. Try again.",
    errorSession: "Your session expired. Sign in again.",
    errorInvalidRequest: "Check the information and try again.",
    errorInvalidCVSS: "Enter a valid CVSS 3.1 vector.",
    errorInvalidState: "The current state does not allow this operation.",
    errorForbidden: "You do not have permission for this operation.",
    errorNotFound: "The requested item was not found.",
    noClientSelected: "Select a client before creating an engagement.",
  },
} as const;

export type Locale = keyof typeof copy;

export function apiErrorMessage(code: string, locale: Locale) {
  const text = copy[locale];
  switch (code) {
    case "unauthorized":
    case "invalid_credentials":
      return text.errorSession;
    case "invalid_request":
      return text.errorInvalidRequest;
    case "invalid_cvss_vector":
      return text.errorInvalidCVSS;
    case "invalid_state":
      return text.errorInvalidState;
    case "forbidden":
      return text.errorForbidden;
    case "not_found":
      return text.errorNotFound;
    default:
      return text.errorGeneric;
  }
}
