export const copy = {
  "pt-BR": {
    language: "Idioma",
    english: "English",
    portuguese: "Português (Brasil)",
    title: "FrameOPS",
    subtitle: "Gestão de projetos de pentest",
    signIn: "Entrar",
    email: "E-mail",
    password: "Senha",
    signInAction: "Iniciar sessão",
    signingIn: "Iniciando sessão…",
    portfolio: "Projetos de pentest",
    clients: "Clientes",
    clientName: "Nome do cliente",
    createClient: "Criar cliente",
    creatingClient: "Criando cliente…",
    selectClient: "Selecione um cliente",
    engagements: "Engagements",
    engagementName: "Nome do engagement",
    createEngagement: "Criar engagement",
    creatingEngagement: "Criando engagement…",
    noClients: "Nenhum cliente encontrado.",
    noEngagements: "Nenhum engagement encontrado.",
    selectEngagement: "Selecione um engagement",
    findings: "Achados",
    findingTitle: "Título do achado",
    description: "Descrição",
    impact: "Impacto",
    remediation: "Remediação",
    reproduction: "Reprodução",
    cvssVector: "Vetor CVSS 3.1",
    createFinding: "Registrar achado",
    creatingFinding: "Registrando achado…",
    noFindings: "Nenhum achado encontrado.",
    selectFinding: "Selecione um achado",
    score: "Score",
    validationState: "Validação",
    remediationState: "Remediação",
    confirmFinding: "Confirmar como aberto",
    confirmingFinding: "Confirmando achado…",
    retests: "Retestes",
    resultState: "Resultado",
    procedure: "Procedimento executado",
    observedResult: "Resultado observado",
    justification: "Justificativa",
    recordRetest: "Registrar reteste",
    recordingRetest: "Registrando reteste…",
    noRetests: "Nenhum reteste registrado.",
    evidence: "Evidências",
    evidenceFile: "Arquivo de evidência",
    captureEvidence: "Capturar evidência",
    capturingEvidence: "Capturando evidência…",
    noEvidence: "Nenhuma evidência capturada.",
    sessionReady: "Sessão iniciada.",
    loading: "Carregando…",
    errorGeneric: "Não foi possível concluir a operação. Tente novamente.",
    errorSession: "Sua sessão expirou. Entre novamente.",
    errorInvalidRequest: "Confira os dados e tente novamente.",
    errorInvalidCVSS: "Informe um vetor CVSS 3.1 válido.",
    errorInvalidState: "O estado atual não permite esta operação.",
    errorEvidenceTooLarge: "O arquivo de evidência excede o limite de 32 MiB.",
    errorArtifactTooLarge: "O artefato de importação excede o limite de 8 MiB.",
    errorInvalidNmapReport: "O artefato não é um relatório XML Nmap aceito.",
    errorDuplicateArtifact: "Este artefato já foi importado neste projeto.",
    errorForbidden: "Você não tem permissão para esta operação.",
    errorNotFound: "O item solicitado não foi encontrado.",
    noClientSelected: "Selecione um cliente antes de criar um engagement.",
    methodologies: "Metodologias",
    methodologyName: "Nome da metodologia",
    sourceName: "Fonte",
    sourceVersion: "Versão da fonte",
    attribution: "Atribuição",
    checklistItemTitle: "Item do checklist",
    checklistObjective: "Objetivo",
    checklistProcedure: "Procedimento",
    createMethodology: "Criar metodologia",
    creatingMethodology: "Criando metodologia…",
    publishMethodology: "Publicar",
    publishingMethodology: "Publicando…",
    selectMethodology: "Selecione uma metodologia publicada",
    noMethodologies: "Nenhuma metodologia publicada encontrada.",
    noMethodologySelected: "Selecione uma metodologia publicada antes de criar um engagement.",
    checklist: "Checklist do engagement",
    noChecklist: "Nenhum checklist selecionado.",
    reports: "Relatórios",
    generateReport: "Gerar DOCX",
    reportFile: "Arquivo DOCX",
    uploadReport: "Enviar relatório",
    uploadingReport: "Enviando relatório…",
    approveReport: "Aprovar revisão",
    approvingReport: "Aprovando revisão…",
    derivePDF: "Derivar PDF",
    derivingPDF: "Derivando PDF…",
    noReports: "Nenhuma revisão de relatório enviada.",
    derivedPDF: "PDF derivado",
    errorReportTooLarge: "O relatório excede o limite de 32 MiB.",
    errorConversionFailed: "Não foi possível derivar o PDF. Tente novamente.",
    overview: "Visão geral",
    projects: "Projetos",
    integrations: "Integrações e CLI",
    workspace: "Workspace do engagement",
    noEngagementSelected: "Selecione ou crie um engagement para começar o trabalho operacional.",
    engagementContext: "Contexto ativo",
    clientContext: "Cliente",
    projectContext: "Projeto",
    workbench: "Bancada operacional",
    workbenchDescription: "Selecione um projeto para concentrar checklist, achados, evidências e entrega.",
    projectSummary: "O trabalho deste engagement aparece aqui, sem misturar fluxos de outras etapas.",
    cliTitle: "CLI online",
    cliDescription: "Use a CLI durante os testes e consolide aqui os registros estruturados do engagement.",
    integrationDescription: "As integrações preservam a mesma API, organização e trilha de auditoria do workspace.",
    selectWorkspace: "Selecionar workspace",
    projectChecklist: "Checklist do projeto",
    loadingWorkspace: "Carregando workspace…",
    operationsDesk: "Mesa de operações",
    pendingActions: "ações pendentes",
    noActiveProject: "Nenhum projeto ativo",
    openFindings: "Abrir achados",
    operationalSummary: "Resumo operacional",
    selectedFindingEvidence: "Evidências do achado",
    selectedFindingRetests: "Retestes do achado",
    checklistItems: "Itens do checklist",
    attackSurface: "Superfície operacional",
    attackSurfaceDescription: "Registros estruturados do escopo e dos achados no contexto ativo.",
    scopeLoaded: "Escopo carregado",
    authorizedScope: "Escopo autorizado",
    structuredRecord: "Registro estruturado",
    currentStateOnly: "Somente estado atual carregado",
    selectOperationalContext: "Selecione o contexto operacional",
    recordFirstFinding: "Registrar o primeiro achado",
    actionQueue: "Fila de ação",
    triageQueue: "Triagem de achados",
    triageQueueHelp: "Novos registros aguardando confirmação",
    retestQueue: "Retestes abertos",
    retestQueueHelp: "Achados em remediação aberta",
    approvalQueue: "Revisões para aprovação",
    approvalQueueHelp: "DOCX armazenados sem aprovação",
    deliveryQueue: "PDFs para derivar",
    deliveryQueueHelp: "Revisões aprovadas sem PDF nesta sessão",
    queueNeedsProject: "A fila aparece após selecionar um projeto.",
    items: "itens",
    clientsDescription: "Organizações atendidas e seus contextos de trabalho.",
    context: "Contexto",
    active: "Ativo",
    select: "Selecionar",
    createClientHelp: "Crie o primeiro cliente para iniciar um projeto.",
    methodologiesDescription: "Biblioteca versionada que origina checklists imutáveis de projeto.",
    status: "Estado",
    action: "Ação",
    projectsDescription: "Selecione um cliente para consultar e abrir seus projetos.",
    projectNeedsClient: "O contexto de cliente limita a lista de projetos.",
    open: "Abrir",
    selectProjectDetail: "Selecione um projeto para consultar seu checklist.",
    findingsDescription: "Selecione um projeto para revisar seus achados.",
    findingsNeedProject: "Os achados são carregados dentro de um projeto ativo.",
    findingDetail: "Detalhe do achado",
    selectFindingDetail: "A seleção abre impacto, remediação e ações.",
    openEvidence: "Abrir evidências",
    evidenceDescription: "Artefatos e retestes vinculados ao achado selecionado.",
    findingContext: "Achado ativo",
    evidenceNeedsFinding: "A cadeia de custódia pertence a um achado específico.",
    custodyChain: "Cadeia de custódia",
    custodyChainDescription: "Arquivos persistidos e sua integridade registrada pela API.",
    artifacts: "artefatos",
    artifact: "Artefato",
    size: "Tamanho",
    captureEvidenceHelp: "Capture um arquivo para iniciar a cadeia deste achado.",
    reportsDescription: "Revisões DOCX, aprovação editorial e derivação do PDF.",
    imports: "Importações",
    importsDescription: "Histórico persistido de inventário recebido pela API deste projeto.",
    importSource: "Origem",
    importReceivedAt: "Recebido em",
    importResult: "Registros resultantes",
    importState: "Estado",
    importRecorded: "Registrada",
    importCreated: "criados",
    importReused: "reutilizados",
    importIgnored: "ignorados",
    importRejected: "rejeitados",
    importsNeedProject: "As importações são carregadas dentro de um projeto ativo.",
    noImports: "Nenhuma importação persistida neste projeto.",
    importsCommand: "Use a CLI online já autenticada para enviar um XML Nmap; este comando não contém credenciais.",
    reportsNeedProject: "As revisões são carregadas dentro de um projeto ativo.",
    revision: "Revisão",
    integrity: "Integridade",
    approved: "Aprovado",
    uploadReportHelp: "Envie a primeira revisão DOCX para iniciar a entrega.",
    projectPlanningTitle: "Planejamento do projeto",
    projectPlanningDescription: "Escopo autorizado, regras e cronograma. Cada alteração de escopo cria uma versão histórica.",
    planningAuthorizationSchedule: "Autorização e cronograma",
    startsOn: "Início",
    endsOn: "Fim",
    rulesOfEngagement: "Regras de engajamento",
    authorizedTargets: "Alvos autorizados (um por linha)",
    exclusions: "Exclusões (uma por linha)",
    milestones: "Marcos",
    milestoneTitle: "Título",
    date: "Data",
    addMilestone: "Adicionar marco",
    remove: "Remover",
    saveScopeVersion: "Salvar nova versão do escopo",
    createPlan: "Criar planejamento",
    currentRecord: "Registro atual",
    scopeVersion: "Versão do escopo",
    immutableChecklistAssigned: "Checklist imutável atribuído ao projeto",
    team: "Equipe",
    projectLeadFallback: "Até que o diretório de membros esteja disponível, o criador do projeto é o lead provisório.",
    activateProject: "Ativar projeto",
    closeProject: "Encerrar projeto",
  },
  en: {
    language: "Language",
    english: "English",
    portuguese: "Português (Brasil)",
    title: "FrameOPS",
    subtitle: "Pentest project management",
    signIn: "Sign in",
    email: "Email",
    password: "Password",
    signInAction: "Start session",
    signingIn: "Starting session…",
    portfolio: "Pentest projects",
    clients: "Clients",
    clientName: "Client name",
    createClient: "Create client",
    creatingClient: "Creating client…",
    selectClient: "Select a client",
    engagements: "Engagements",
    engagementName: "Engagement name",
    createEngagement: "Create engagement",
    creatingEngagement: "Creating engagement…",
    noClients: "No clients found.",
    noEngagements: "No engagements found.",
    selectEngagement: "Select an engagement",
    findings: "Findings",
    findingTitle: "Finding title",
    description: "Description",
    impact: "Impact",
    remediation: "Remediation",
    reproduction: "Reproduction",
    cvssVector: "CVSS 3.1 vector",
    createFinding: "Record finding",
    creatingFinding: "Recording finding…",
    noFindings: "No findings found.",
    selectFinding: "Select a finding",
    score: "Score",
    validationState: "Validation",
    remediationState: "Remediation",
    confirmFinding: "Confirm as open",
    confirmingFinding: "Confirming finding…",
    retests: "Retests",
    resultState: "Result",
    procedure: "Executed procedure",
    observedResult: "Observed result",
    justification: "Justification",
    recordRetest: "Record retest",
    recordingRetest: "Recording retest…",
    noRetests: "No retests recorded.",
    evidence: "Evidence",
    evidenceFile: "Evidence file",
    captureEvidence: "Capture evidence",
    capturingEvidence: "Capturing evidence…",
    noEvidence: "No evidence captured.",
    sessionReady: "Session started.",
    loading: "Loading…",
    errorGeneric: "We could not complete the operation. Try again.",
    errorSession: "Your session expired. Sign in again.",
    errorInvalidRequest: "Check the information and try again.",
    errorInvalidCVSS: "Enter a valid CVSS 3.1 vector.",
    errorInvalidState: "The current state does not allow this operation.",
    errorEvidenceTooLarge: "The evidence file exceeds the 32 MiB limit.",
    errorArtifactTooLarge: "The import artifact exceeds the 8 MiB limit.",
    errorInvalidNmapReport: "The artifact is not an accepted Nmap XML report.",
    errorDuplicateArtifact: "This artifact has already been imported into this project.",
    errorForbidden: "You do not have permission for this operation.",
    errorNotFound: "The requested item was not found.",
    noClientSelected: "Select a client before creating an engagement.",
    methodologies: "Methodologies",
    methodologyName: "Methodology name",
    sourceName: "Source",
    sourceVersion: "Source version",
    attribution: "Attribution",
    checklistItemTitle: "Checklist item",
    checklistObjective: "Objective",
    checklistProcedure: "Procedure",
    createMethodology: "Create methodology",
    creatingMethodology: "Creating methodology…",
    publishMethodology: "Publish",
    publishingMethodology: "Publishing…",
    selectMethodology: "Select a published methodology",
    noMethodologies: "No published methodologies found.",
    noMethodologySelected: "Select a published methodology before creating an engagement.",
    checklist: "Engagement checklist",
    noChecklist: "No checklist selected.",
    reports: "Reports",
    generateReport: "Generate DOCX",
    reportFile: "DOCX file",
    uploadReport: "Upload report",
    uploadingReport: "Uploading report…",
    approveReport: "Approve revision",
    approvingReport: "Approving revision…",
    derivePDF: "Derive PDF",
    derivingPDF: "Deriving PDF…",
    noReports: "No report revisions uploaded.",
    derivedPDF: "Derived PDF",
    errorReportTooLarge: "The report exceeds the 32 MiB limit.",
    errorConversionFailed: "We could not derive the PDF. Try again.",
    overview: "Overview",
    projects: "Projects",
    integrations: "Integrations and CLI",
    workspace: "Engagement workspace",
    noEngagementSelected: "Select or create an engagement to begin operational work.",
    engagementContext: "Active context",
    clientContext: "Client",
    projectContext: "Project",
    workbench: "Operations workbench",
    workbenchDescription: "Select a project to focus its checklist, findings, evidence, and delivery.",
    projectSummary: "This engagement's work appears here without mixing work from other stages.",
    cliTitle: "Online CLI",
    cliDescription: "Use the CLI during testing and consolidate the engagement's structured records here.",
    integrationDescription: "Integrations retain the same API, organization, and audit trail as the workspace.",
    selectWorkspace: "Select workspace",
    projectChecklist: "Project checklist",
    loadingWorkspace: "Loading workspace…",
    operationsDesk: "Operations desk",
    pendingActions: "pending actions",
    noActiveProject: "No active project",
    openFindings: "Open findings",
    operationalSummary: "Operational summary",
    selectedFindingEvidence: "Finding evidence",
    selectedFindingRetests: "Finding retests",
    checklistItems: "Checklist items",
    attackSurface: "Operational surface",
    attackSurfaceDescription: "Structured scope and finding records in the active context.",
    scopeLoaded: "Scope loaded",
    authorizedScope: "Authorized scope",
    structuredRecord: "Structured record",
    currentStateOnly: "Current loaded state only",
    selectOperationalContext: "Select the operational context",
    recordFirstFinding: "Record the first finding",
    actionQueue: "Action queue",
    triageQueue: "Finding triage",
    triageQueueHelp: "New records awaiting confirmation",
    retestQueue: "Open retests",
    retestQueueHelp: "Findings with open remediation",
    approvalQueue: "Revisions to approve",
    approvalQueueHelp: "Stored DOCX files without approval",
    deliveryQueue: "PDFs to derive",
    deliveryQueueHelp: "Approved revisions without a PDF in this session",
    queueNeedsProject: "The queue appears after selecting a project.",
    items: "items",
    clientsDescription: "Served organizations and their work contexts.",
    context: "Context",
    active: "Active",
    select: "Select",
    createClientHelp: "Create the first client to start a project.",
    methodologiesDescription: "Versioned library that originates immutable project checklists.",
    status: "Status",
    action: "Action",
    projectsDescription: "Select a client to review and open its projects.",
    projectNeedsClient: "The client context scopes the project list.",
    open: "Open",
    selectProjectDetail: "Select a project to review its checklist.",
    findingsDescription: "Select a project to review its findings.",
    findingsNeedProject: "Findings are loaded within an active project.",
    findingDetail: "Finding detail",
    selectFindingDetail: "Selection opens impact, remediation, and actions.",
    openEvidence: "Open evidence",
    evidenceDescription: "Artifacts and retests linked to the selected finding.",
    findingContext: "Active finding",
    evidenceNeedsFinding: "The custody chain belongs to a specific finding.",
    custodyChain: "Custody chain",
    custodyChainDescription: "Persisted files and integrity recorded by the API.",
    artifacts: "artifacts",
    artifact: "Artifact",
    size: "Size",
    captureEvidenceHelp: "Capture a file to begin this finding's chain.",
    reportsDescription: "DOCX revisions, editorial approval, and PDF derivation.",
    imports: "Imports",
    importsDescription: "Persisted inventory history received by this project's API.",
    importSource: "Source",
    importReceivedAt: "Received at",
    importResult: "Resulting records",
    importState: "State",
    importRecorded: "Recorded",
    importCreated: "created",
    importReused: "reused",
    importIgnored: "ignored",
    importRejected: "rejected",
    importsNeedProject: "Imports are loaded within an active project.",
    noImports: "No imports are persisted for this project.",
    importsCommand: "Use the already authenticated online CLI to submit an Nmap XML file; this command contains no credentials.",
    reportsNeedProject: "Revisions are loaded within an active project.",
    revision: "Revision",
    integrity: "Integrity",
    approved: "Approved",
    uploadReportHelp: "Upload the first DOCX revision to begin delivery.",
    projectPlanningTitle: "Project planning",
    projectPlanningDescription: "Authorized scope, rules, and schedule. Each scope change creates a historical version.",
    planningAuthorizationSchedule: "Authorization and schedule",
    startsOn: "Start",
    endsOn: "End",
    rulesOfEngagement: "Rules of engagement",
    authorizedTargets: "Authorized targets (one per line)",
    exclusions: "Exclusions (one per line)",
    milestones: "Milestones",
    milestoneTitle: "Title",
    date: "Date",
    addMilestone: "Add milestone",
    remove: "Remove",
    saveScopeVersion: "Save new scope version",
    createPlan: "Create plan",
    currentRecord: "Current record",
    scopeVersion: "Scope version",
    immutableChecklistAssigned: "Immutable checklist assigned to the project",
    team: "Team",
    projectLeadFallback: "Until the member directory is available, the project creator is the provisional lead.",
    activateProject: "Activate project",
    closeProject: "Close project",
  },
} as const;

export type Locale = keyof typeof copy;

export function apiErrorMessage(code: string, locale: Locale) {
  const text = copy[locale];
  switch (code) {
    case "unauthorized":
    case "invalid_credentials":
      return text.errorSession;
    case "invalid_request":
      return text.errorInvalidRequest;
    case "invalid_cvss_vector":
      return text.errorInvalidCVSS;
    case "invalid_state":
      return text.errorInvalidState;
    case "evidence_too_large":
      return text.errorEvidenceTooLarge;
    case "artifact_too_large":
      return text.errorArtifactTooLarge;
    case "invalid_nmap_report":
      return text.errorInvalidNmapReport;
    case "duplicate_artifact":
      return text.errorDuplicateArtifact;
    case "report_too_large":
      return text.errorReportTooLarge;
    case "conversion_failed":
      return text.errorConversionFailed;
    case "forbidden":
      return text.errorForbidden;
    case "not_found":
      return text.errorNotFound;
    default:
      return text.errorGeneric;
  }
}
